name: Build and Test

on:
  pull_request:
  workflow_dispatch:

env:
  LIVEBLOCKS_API_KEY: ${{ secrets.LIVEBLOCKS_API_KEY }}

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn run lint

      - name: Build the project
        run: yarn run build

      - name: Type-check
        run: yarn run type-check

      - name: Run tests
        run: yarn run test
